version = 0.1

[default.deploy.parameters]
stack_name = "sam-app"
resolve_s3 = true
s3_prefix = "sam-app"
region = "us-east-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
disable_rollback = true
parameter_overrides = "ExternalId=\"\" InventoryRoleName=\"InventoryReadRole\" ExistingCognitoUserPoolId=\"us-east-1_CiQtVfFnM\" ExistingCognitoClientId=\"39v2nj1ueoajpeqfrckpthd0go\" CognitoRegion=\"us-east-1\""
image_repositories = []

[default.global.parameters]
region = "us-east-1"
